version: 2
jobs:
  build-test:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
        environment:
          VERSION_PREFIX: "2.0"
      - image: mongo:3.6
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Build package
          command: |
            export VERSION="${VERSION_PREFIX}.${CIRCLE_BUILD_NUM}"
            dotnet pack -c Release -o artifacts src/MongoDB.Extensions.Repository /p:PackageVersion=$VERSION /p:Version=$VERSION  /p:AssemblyVersion=$VERSION
      - run:
          name: Test
          command: dotnet test -c Release test/MongoDB.Extensions.Repository.Tests
      - run:
          name: Integration Test
          command: dotnet test -c Release test/MongoDB.Extensions.Repository.IntegrationTests
      - persist_to_workspace:
          root: ~/app
          paths: .
          
  publish:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: ~/app
      - run: dotnet nuget push artifacts/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json

workflows:
  version: 2
  build-test-publish:
    jobs:
      - build-test
      - publish:
          requires:
            - build-test
          filters:
            branches:
              only: master